package repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Data access layer for atomically opening a new onboarding case together with its
 * new client, address, initial document checklist entries, and officer assignment.
 */
public class OnboardingRepository {
    private static final Logger logger = LoggerFactory.getLogger(OnboardingRepository.class);

    /** Client attributes required to open a new case. */
    public static class ClientInput {
        public String fullName;
        public String clientType;
        public String nationality;
        public String dateOfBirth;
        public String countryOfBirth;
        public String taxResidency;
        public String occupation;
        public String employer;
        public String mainSourceOfFunds;
        public String annualIncomeBand;
        public String status;
        public boolean isActive;
        public String username;
        public String passwordHash;
    }

    /** Address attributes required to open a new case. */
    public static class AddressInput {
        public String addressType;
        public String line1;
        public String line2;
        public String city;
        public String state;
        public String postcode;
        public String country;
        public String isCurrent;
    }

    /** Identifiers generated by an atomic case-opening operation. */
    public static class OpenCaseResult {
        public final int clientId;
        public final int caseId;

        public OpenCaseResult(int clientId, int caseId) {
            this.clientId = clientId;
            this.caseId = caseId;
        }
    }

    /**
     * Creates a client, its address, an onboarding case, and its initial submitted
     * documents, optionally assigning a compliance officer — all within a single
     * transaction, rolling back entirely on any failure.
     *
     * @param client      new client attributes
     * @param address     new client's address attributes
     * @param productType requested product type
     * @param dueDate     case due date in yyyy-MM-dd format, or null
     * @param officerId   compliance officer to assign, or null to leave unassigned
     * @param docTypeIds  document type ids already provided at onboarding, or null
     * @return the generated client id and case id
     * @throws SQLException when persistence fails
     */
    public OpenCaseResult openCase(ClientInput client, AddressInput address, String productType, String dueDate,
            Integer officerId, List<Integer> docTypeIds) throws SQLException {
        try (Connection conn = DatabaseConnection.getConnection()) {
            conn.setAutoCommit(false);
            try {
                int clientId = insertClient(conn, client);
                insertAddress(conn, clientId, address);
                int caseId = insertCase(conn, clientId, productType, dueDate, officerId);
                if (docTypeIds != null) {
                    for (int docTypeId : docTypeIds) {
                        insertDocument(conn, caseId, docTypeId);
                    }
                }
                conn.commit();
                logger.info(
                        "Onboarding case opened: clientId={} caseId={} product={} officerId={} documentCount={}",
                        clientId, caseId, productType, officerId, docTypeIds == null ? 0 : docTypeIds.size());
                return new OpenCaseResult(clientId, caseId);
            } catch (SQLException | RuntimeException e) {
                conn.rollback();
                logger.error("Onboarding case opening rolled back: reason={}", e.getMessage());
                throw e;
            }
        }
    }

    private int insertClient(Connection conn, ClientInput c) throws SQLException {
        String sql = "INSERT INTO client (full_name, client_type, nationality, country_of_birth, date_of_birth, "
                + "tax_residency, occupation, employer, main_source_of_funds, annual_income_band, status, is_active, "
                + "username, password_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, c.fullName);
            ps.setString(2, c.clientType);
            ps.setString(3, c.nationality);
            ps.setString(4, c.countryOfBirth);
            ps.setString(5, c.dateOfBirth);
            ps.setString(6, c.taxResidency);
            setNullableString(ps, 7, c.occupation);
            setNullableString(ps, 8, c.employer);
            setNullableString(ps, 9, c.mainSourceOfFunds);
            setNullableString(ps, 10, c.annualIncomeBand);
            ps.setString(11, c.status);
            ps.setBoolean(12, c.isActive);
            ps.setString(13, c.username);
            ps.setString(14, c.passwordHash);
            ps.executeUpdate();
            try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getInt(1);
                }
            }
        }
        throw new SQLException("Failed to create client");
    }

    private void insertAddress(Connection conn, int clientId, AddressInput a) throws SQLException {
        String sql = "INSERT INTO client_address (client_id, address_type, line1, line2, city, country, state, "
                + "postcode, is_current) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, clientId);
            ps.setString(2, a.addressType);
            ps.setString(3, a.line1);
            setNullableString(ps, 4, a.line2);
            ps.setString(5, a.city);
            ps.setString(6, a.country);
            setNullableString(ps, 7, a.state);
            setNullableString(ps, 8, a.postcode);
            ps.setString(9, a.isCurrent);
            ps.executeUpdate();
        }
    }

    private int insertCase(Connection conn, int clientId, String productType, String dueDate, Integer officerId)
            throws SQLException {
        String sql = "INSERT INTO onboarding_case (client_id, opened_date, product_type, case_status, due_date, "
                + "assigned_officer_id) VALUES (?, CURRENT_TIMESTAMP, ?, 'OPEN', ?, ?)";
        try (PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, clientId);
            ps.setString(2, productType);
            if (dueDate == null || dueDate.isEmpty()) {
                ps.setNull(3, Types.DATE);
            } else {
                ps.setString(3, dueDate);
            }
            if (officerId == null) {
                ps.setNull(4, Types.INTEGER);
            } else {
                ps.setInt(4, officerId);
            }
            ps.executeUpdate();
            try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getInt(1);
                }
            }
        }
        throw new SQLException("Failed to open onboarding case");
    }

    private void insertDocument(Connection conn, int caseId, int docTypeId) throws SQLException {
        String sql = "INSERT INTO document (case_id, doc_type_id, submission_date, verified_flag) "
                + "VALUES (?, ?, CURDATE(), false)";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, caseId);
            ps.setInt(2, docTypeId);
            ps.executeUpdate();
        }
    }

    private void setNullableString(PreparedStatement ps, int index, String value) throws SQLException {
        if (value == null || value.isEmpty()) {
            ps.setNull(index, Types.VARCHAR);
        } else {
            ps.setString(index, value);
        }
    }
}
